import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { Sticker } from '../sticker.model';
import { StickersStore } from './stickers.store';

@Injectable({ providedIn: 'root' })
export class StickersService {
  constructor(private stickersStore: StickersStore, private http: HttpClient) {}

  get(): Observable<Sticker[]> {
    return this.http.get<Sticker[]>('http://localhost:3000/stickers').pipe(
      tap((entities) => {
        this.stickersStore.set(entities);
      })
    );
  }

  // 👇 Also generated by Akita, but works only in memory. Strange choice. We don't want them now.
  // add(sticker: Sticker): void {
  //   this.stickersStore.add(sticker);
  // }
  //
  // update(id: ID, sticker: Partial<Sticker>): void {
  //   this.stickersStore.update(id, sticker);
  // }
  //
  // remove(id: ID): void {
  //   this.stickersStore.remove(id);
  // }
}
